### ISSUE TITLE
not in sync error 

### ISSUE THREAD

**Issue by Jingxuan31** [NVSL/TAZI#4]
Hi Michael
I am testing my robot on TAZI and Arduino for ERSP right now. My code complies but not uploaded correctly.
The error is
:avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
The first day when I got this error, I just plug USB out and put in agin to fix it.
But now I got the same error but I am not able to fix it.
My task is pretty easy--just drawing a happy face.

Best
Julia

**Comment by MichaelMGonzalez** [comment]
Hi Julia,

That particular error message does not look like an error that TAZI itself might produce. Did you receive that when trying to upload your code via the TAZI IDE or Arduino IDE? 

TAZI tries to use the last settings used by Arduino when it tries to upload to a board. 
Could you post your Arduino's configuration here?

I'm interested in seeing your: 
Comm Port Selection
Board Selection
Programmer Selection
